/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.suaempresa.locadora.ui;

import com.suaempresa.locadora.model.GerenciadorClientes;
import com.suaempresa.locadora.model.GerenciadorVeiculos;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author enzo
 */
public class HomePanel extends javax.swing.JPanel {

    private GerenciadorClientes gerenciadorClientes;
    private GerenciadorVeiculos gerenciadorVeiculos;
    
    /**
     * Creates new form HomePanel
     */
public HomePanel(GerenciadorClientes gc, GerenciadorVeiculos gv) {
        this.gerenciadorClientes = gc;
        this.gerenciadorVeiculos = gv;
        initComponents(); 
        
        this.setBorder(new EmptyBorder(50, 50, 50, 50));

        this.setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS)); 
        this.removeAll(); 

        this.add(Box.createVerticalStrut(20)); 

        
        if (jLabel10 != null) { 
            jLabel10.setAlignmentX(Component.CENTER_ALIGNMENT); 
            this.add(jLabel10);
        }
        this.add(Box.createVerticalStrut(5)); 

        if (jLabel12 != null) { 
            jLabel12.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel12);
        }
        this.add(Box.createVerticalStrut(40)); 

        
        this.add(createAlignedLabelPair(jLabel2, lblTotalClientes)); 
        this.add(Box.createVerticalStrut(15)); 

        this.add(createAlignedLabelPair(jLabel3, lblTotalVeiculos));
        this.add(Box.createVerticalStrut(15));

        this.add(createAlignedLabelPair(jLabel4, lblVeiculosDisponiveis)); 
        this.add(Box.createVerticalStrut(15));

        this.add(createAlignedLabelPair(jLabel5, lblVeiculosLocados)); 
        this.add(Box.createVerticalStrut(40)); 

        
        if (jLabel7 != null) {
            jLabel7.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel7);
            this.add(Box.createVerticalStrut(5)); 
        }
        if (jLabel8 != null) {
            jLabel8.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel8);
            this.add(Box.createVerticalStrut(5));
        }
        if (jLabel9 != null) {
            jLabel9.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel9);
        }

        this.add(Box.createVerticalGlue()); 

        this.revalidate(); 
        this.repaint();   

        carregarEstatisticas(); 
    }
    
    public void carregarEstatisticas() {
    int totalClientes = gerenciadorClientes.listarTodosClientes().size();
    int totalVeiculos = gerenciadorVeiculos.listarTodosVeiculos().size();
    int veiculosDisponiveis = gerenciadorVeiculos.listarVeiculosDisponiveisParaLocacao().size();
    int veiculosLocados = gerenciadorVeiculos.listarVeiculosLocados().size();

   
    lblTotalClientes.setText(String.valueOf(totalClientes)); 
    lblTotalVeiculos.setText(String.valueOf(totalVeiculos));
    lblVeiculosDisponiveis.setText(String.valueOf(veiculosDisponiveis));
    lblVeiculosLocados.setText(String.valueOf(veiculosLocados));
}
    
    private JPanel createAlignedLabelPair(JLabel textLabel, JLabel numberLabel) {
        JPanel pairPanel = new JPanel();
        
        pairPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0)); 
        pairPanel.setOpaque(false); 

        if (textLabel != null) {
            pairPanel.add(textLabel);
        }
        if (numberLabel != null) {
            pairPanel.add(numberLabel);
        }
        
        pairPanel.setAlignmentX(Component.CENTER_ALIGNMENT); 
        return pairPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelEstatisticasGrid = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalClientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalVeiculos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblVeiculosDisponiveis = new javax.swing.JLabel();
        lblVeiculosLocados = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Sistema Locadora");

        setBackground(new java.awt.Color(240, 238, 230));
        setPreferredSize(new java.awt.Dimension(843, 613));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Veículos Disponíveis:");
        add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Veiculos Locados:");
        add(jLabel5);

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sistema Locadora");
        add(jLabel11);

        panelEstatisticasGrid.setBackground(new java.awt.Color(240, 238, 230));
        panelEstatisticasGrid.setLayout(new java.awt.GridLayout(2, 2, 0, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total de Veículos:");
        panelEstatisticasGrid.add(jLabel3);

        lblTotalClientes.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblTotalClientes.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalClientes.setText("2222");
        panelEstatisticasGrid.add(lblTotalClientes);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total de Clientes:");
        panelEstatisticasGrid.add(jLabel2);

        lblTotalVeiculos.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblTotalVeiculos.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalVeiculos.setText("2222");
        panelEstatisticasGrid.add(lblTotalVeiculos);

        add(panelEstatisticasGrid);

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Home");
        add(jLabel12);

        lblVeiculosDisponiveis.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblVeiculosDisponiveis.setForeground(new java.awt.Color(0, 0, 0));
        lblVeiculosDisponiveis.setText("222");
        add(lblVeiculosDisponiveis);

        lblVeiculosLocados.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblVeiculosLocados.setForeground(new java.awt.Color(0, 0, 0));
        lblVeiculosLocados.setText("222");
        add(lblVeiculosLocados);

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Enzo Spironelli Pinheiro - GRR20243314");
        add(jLabel9);

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Linguagem de Programação Orientada a Objetos 1 - DS131");
        add(jLabel8);

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Professor Rafael Romualdo Wandresen");
        add(jLabel7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblTotalClientes;
    private javax.swing.JLabel lblTotalVeiculos;
    private javax.swing.JLabel lblVeiculosDisponiveis;
    private javax.swing.JLabel lblVeiculosLocados;
    private javax.swing.JPanel panelEstatisticasGrid;
    // End of variables declaration//GEN-END:variables
}
