/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.suaempresa.locadora.view;



import com.suaempresa.locadora.model.Veiculo; 
import com.suaempresa.locadora.ui.tables.VeiculoTableModel; 
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent; 
import javax.swing.event.ListSelectionListener; 

import java.awt.Component; 
import java.util.ArrayList;
import javax.swing.Box; 
import javax.swing.JLabel; 
import javax.swing.JPanel; 
import javax.swing.JScrollPane; 
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;


/**
 *
 * @author enzo
 */
public class VeiculoDevolucaoPanel extends javax.swing.JPanel {


    private VeiculoTableModel veiculoTableModel; 
    private Veiculo veiculoSelecionado;
    
    
    /**
     * Creates new form VeiculoDevolucaoPanel
     */
    public VeiculoDevolucaoPanel() {
 
        initComponents(); 
        this.veiculoTableModel = new VeiculoTableModel(new ArrayList<>(), "DEVOLUCAO");
        this.setBorder(new EmptyBorder(30, 50, 30, 50));

        
        this.setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS)); 
        this.removeAll(); 

        this.add(Box.createVerticalStrut(20)); 

        
        if (jLabel1 != null) { 
            jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT); 
            this.add(jLabel1);
        }
        this.add(Box.createVerticalStrut(5)); 

        if (jLabel2 != null) { 
            jLabel2.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel2);
        }
        this.add(Box.createVerticalStrut(30)); 

        
        if (jLabel3 != null) { 
            jLabel3.setAlignmentX(Component.CENTER_ALIGNMENT);
            this.add(jLabel3);
        }
        this.add(Box.createVerticalStrut(10)); 

       
        if (jScrollPane1 != null) {
            jScrollPane1.setAlignmentX(Component.CENTER_ALIGNMENT); 
            jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 300)); 
            this.add(jScrollPane1);
        }
        this.add(Box.createVerticalStrut(30)); 

        // --- Botão de Ação ---
        if (btnDevolverVeiculo != null) {
            btnDevolverVeiculo.setAlignmentX(Component.CENTER_ALIGNMENT);
            btnDevolverVeiculo.setPreferredSize(new java.awt.Dimension(200, 40)); 
            this.add(btnDevolverVeiculo);
        }
        this.add(Box.createVerticalStrut(20)); 

        this.add(Box.createVerticalGlue()); 

        this.revalidate(); 
        this.repaint();    

        
  
        jTableVeiculosLocados.setModel(veiculoTableModel);
        jTableVeiculosLocados.setAutoCreateRowSorter(true);
        addTableSelectionListener();
    }
    
   
    
    private void addTableSelectionListener() {
    jTableVeiculosLocados.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting() && jTableVeiculosLocados.getSelectedRow() != -1) {
                int selectedRow = jTableVeiculosLocados.getSelectedRow();
                int modelRow = jTableVeiculosLocados.convertRowIndexToModel(selectedRow);
                veiculoSelecionado = veiculoTableModel.getVeiculoAt(modelRow); 
                
                
            } else {
                veiculoSelecionado = null; 
            }
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDevolverVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculosLocados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        btnDevolverVeiculo.setBackground(new java.awt.Color(14, 20, 30));
        btnDevolverVeiculo.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnDevolverVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolverVeiculo.setText("Devolver Veículo");
        btnDevolverVeiculo.setPreferredSize(new java.awt.Dimension(182, 50));
        btnDevolverVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverVeiculoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(14, 20, 30));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTableVeiculosLocados.setBackground(new java.awt.Color(14, 20, 30));
        jTableVeiculosLocados.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jTableVeiculosLocados.setForeground(new java.awt.Color(255, 255, 255));
        jTableVeiculosLocados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVeiculosLocados.setGridColor(new java.awt.Color(14, 20, 30));
        jTableVeiculosLocados.setRowHeight(50);
        jScrollPane1.setViewportView(jTableVeiculosLocados);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Veículos Locados:");

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sistema Locadora");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Devolver veículo");

        setBackground(new java.awt.Color(240, 238, 230));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverVeiculoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDevolverVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculosLocados;
    // End of variables declaration//GEN-END:variables
}
